name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy latest backend image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan lucas.congras.takima.cloud >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        env:
          HOST: lucas.congras.takima.cloud
          USER: admin
          #ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml \
            --user=admin \
            --private-key=~/.ssh/id_rsa